---
kind: pipeline
type: docker
name: amd64

platform:
  arch: amd64

steps:
  - name: Build
    image: rust
    commands: 
      - cargo build --release
---
kind: pipeline
type: docker
name: arm

platform:
  arch: arm

steps:
  - name: Build
    image: rust
    commands: 
      - cargo build --release